### ISSUE TITLE
Publish the documentation for google-cloud-python-happybase.

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python-happybase#17]
Previously they were hosted at 
https://googlecloudplatform.github.io/google-cloud-python/stable/happybase-package.html but now that link 404s.

**Comment by dhermes** [comment]
As of right now, they are nowhere, though `tox -e docs` builds them to make sure they are up to date.

**Comment by tswast** [comment]
I talked with @jonparrott about this. We need to release the docs for this package separately from the rest of google-cloud-python, since the docs are also released under a different license from the rest of the google-cloud-python docs.

**Comment by dhermes** [comment]
http://google-cloud-python-happybase.readthedocs.io/en/latest/
