### ISSUE TITLE
Performing a google.cloud.happybase Bigtable RowKeyRegexFilter Scan Not Working

### ISSUE THREAD

**Issue by danigosa** [GoogleCloudPlatform/google-cloud-python-happybase#21]
I'm trying to do row filtering by Key regex filter, everything is working like a charm (filter by prefix, filter by key start and stop range, by key, by keys) but I can't get it working passing in the `RowKeyRegexFilter` as filter, it just returns all the keys as an empty keys scan:

```python
# all the boilerplate to create a happybase connection skipped 
t = connection.table("sometable")
t.put(
    b'row1',
    {
       b"family1:col2": b".1",
       b"family2:col2": b".12",
    }
)
t.put(
    b'row2',
    {
       b"family1:col2": b".2",
       b"family2:col2": b".22",
    }
)
t.put(
    b'row3',
    {
       b"family1:col2": b".3",
       b"family2:col2": b".32",
    }
)
rows = t.scan(
    filter=RowKeyRegexFilter(b'.+3')
)
print(len([i for i in rows])
```

That gives always 3, no matter if you put `(nomatchforsure)+` as regex, I could not find any documentation with a working example, and the most amazing thing is that `google.cloud.happybase.table.Table.rows` performs a filter by row key always with `RowKeyRegexFilter`, but passing regex into `rows` method instead of real rows keys don't give regex filtering either, you can see it

here: [https://github.com/GoogleCloudPlatform/google-cloud-python-happybase/blob/master/src/google/cloud/happybase/table.py#L197][1]

and here: [https://github.com/GoogleCloudPlatform/google-cloud-python-happybase/blob/master/src/google/cloud/happybase/table.py#L971][2]

Any help on this would be very appreciated

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python-happybase/blob/4409d383f8207cf95726dbf9349acc16bfff44b9/src/google/cloud/happybase/table.py#L197
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python-happybase/blob/4409d383f8207cf95726dbf9349acc16bfff44b9/src/google/cloud/happybase/table.py#L971

**Comment by danigosa** [comment]
Hi, just solved it and realized the actual bug/problem: it happend with the **BigTable emulator (Google Cloud SDK 149.0.0)** so although it is possible to workaround it with actual dev or prod instances is kind of annoying to buy an instance for a so simple piece of test code.

**Comment by danigosa** [comment]
UPDATE: It's actually annotated in the docs as noticed by @gary-elliott: https://cloud.google.com/bigtable/docs/emulator#filters Regular expressions must contain only valid UTF-8 characters, unlike the actual Cloud Bigtable service which can process regular expressions as arbitrary bytes. Although something simple like (notmatchforsure)+is not working either although it seems containing valid UTF8 characters, on my testings I would say it is not limited, but generally speaking not working. Anyway is correctly warned in docs.

**Comment by dhermes** [comment]
@garye @danigosa Any suggestions on something we can do (in the codebase) to make this a better experience?

**Comment by danigosa** [comment]
@dhermes Hi, in my experience the docs are misleading as it states that regex filter is "limited" for the emulator but it actually does not work for very basic filters, of course with valid UTF-8 characters. My suggestion would be, if there is no plan to implement the regex filter (for my case the most important one) in the emulator to improve the docs section saying that regex filter is not expected to work at all.

**Comment by dhermes** [comment]
@danigosa Which docs are you referring to? This library has no impact on the emulator docs.

**Comment by danigosa** [comment]
@dhermes https://cloud.google.com/bigtable/docs/emulator#filters

**Comment by dhermes** [comment]
@danigosa Those docs explicitly state:

> Issues related to Cloud Bigtable emulator development are tracked in the [google-cloud-go][1] GitHub repository, where you can file feature requests or comment on existing requests.

I'm going to close this out and redirect your inquiry there. There's nothing we can do within our Python library to fix this issue but it sounds like the Golang team owns the emulator (and probably those docs as well).

[1]: https://github.com/GoogleCloudPlatform/google-cloud-go/labels/bigtable
