### ISSUE TITLE
Update homepage and API URLs in README

### ISSUE THREAD

**Issue by mbrukman** [GoogleCloudPlatform/google-cloud-python-happybase#25]
The [`README.rst`](https://raw.githubusercontent.com/GoogleCloudPlatform/google-cloud-python-happybase/master/README.rst) file currently has the following links:

> *  [Homepage](https://googlecloudplatform.github.io/google-cloud-python/)
> *  [API Documentation](https://googlecloudplatform.github.io/google-cloud-python/stable/)

However, those are pointing to the generic `google-cloud-python` site and API, not the `google-cloud-python-happybase` site and APIs.

For APIs, looks like the correct URL is http://google-cloud-python-happybase.readthedocs.io/ but I'm not sure if there's an equivalent URL for the homepage, or if that should just be omitted.

**Comment by tseaver** [comment]
We aren't currently populating docs at https://googlecloudplatform.github.io/google-cloud-python-happybase/.  I would say we could just link the RTD docs as "Documentation".
