### ISSUE TITLE
Need a separate release

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python-happybase#3]
Probably synched with a `0.19.0` release of `gcloud-python`.

**Comment by dhermes** [comment]
@tseaver Do we want to restart this repo at a lower number or no big deal?

**Comment by tseaver** [comment]
I would be inclined to make the initial release `0.19.0`, and then let it evolve naturally afterwards, independent of `gcloud-python`/`google-cloud-python`.

**Comment by dhermes** [comment]
SGTM

**Comment by tswast** [comment]
What is the package name? I should probably update the Cloud Bigtable samples when the new package is out. https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/bigtable/hello_happybase

**Comment by tseaver** [comment]
@tswast The PyPI name is / will be [`google-cloud-happybase`](https://github.com/GoogleCloudPlatform/google-cloud-python-happybase/blob/5aad71e5088fd8ec4c9d97ad95e30de12b174797/setup.py#L18).  Imports will be from the `google.cloud.happybase` package:

```python
from google.cloud.happybase import Client
```

**Comment by dhermes** [comment]
Once Travis speeds up this build should push `0.20.0` to PyPI: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python-happybase/builds/163836514

**Comment by dhermes** [comment]
Hooray!

https://pypi.python.org/pypi/google-cloud-happybase/0.20.0
