### ISSUE TITLE
Needs to be updated to use latest bigtable

### ISSUE THREAD

**Issue by theacodes** [GoogleCloudPlatform/google-cloud-python-happybase#33]
See https://travis-ci.org/GoogleCloudPlatform/python-docs-samples/builds/347706464#L1091

**Comment by tseaver** [comment]
Via #36.

Likely needs a release.

**Comment by tseaver** [comment]
Hmm, #34 has other changes which may be relevant.

**Comment by sduskis** [comment]
This was done.
