### ISSUE TITLE
README links to invalid 'Homepage' and 'API Documentation' URLs

### ISSUE THREAD

**Issue by ncouture** [GoogleCloudPlatform/google-cloud-python-happybase#8]

**Comment by dhermes** [comment]
Thanks for the heads up. We are blocked on https://github.com/GoogleCloudPlatform/google-cloud-python breaking the release into tiny packages

**Comment by dhermes** [comment]
I hope to have that work done this week.

**Comment by dhermes** [comment]
Fixed by #15
